#!/usr/bin/env node
// One-off generator for data/world-map-geo.js (committed output; rerun only to
// change the country set or basemap resolution).
//
// This is a SIBLING to build-map.js, not a replacement for it: data/world-map.js
// is loaded by 12 pages and stays on its 110m SVG-path shape. This script exists
// because illustrated-journey-dashboard.html alone moved its map rendering to
// MapLibre GL JS (DEV-13 D18, superseding D13's no-mapping-library decision) and
// MapLibre needs real GeoJSON geometry, not SVG path strings.
//
// Dev-only dependencies — install anywhere and point NODE_PATH at it:
//   npm i topojson-client world-atlas d3-geo
//   node scripts/build-map-geo.js [path-to-node_modules]
//
// Output: data/world-map-geo.js -> window.LAUNCH_MAP_GEO = GeoJSON FeatureCollection,
// one feature per country, properties = { iso3, name }.
// Uses Natural Earth 50m (public domain) via the world-atlas package — one
// resolution step up from build-map.js's 110m, chosen because a page-specific
// basemap can carry more detail without the 12-page blast radius a change to
// data/world-map.js would have (see dev-13-resistance-handover.md D17).
//
// Country set is intentionally IDENTICAL to build-map.js's NUM_TO_A3 (not a
// superset) — data/world-map.js stays the single source of truth for "which
// countries count as drawn" (sitesFor's filter, drawnCount, curUndrawn, the
// validator's undrawn-country warning). This file supplies geometry only, at
// the same scope. See D17 for the alternative considered and rejected.

const path = require("path");
const fs = require("fs");

const extra = process.argv[2];
if (extra) module.paths.unshift(path.resolve(extra));

const topojson = require("topojson-client");
const world = require(require.resolve("world-atlas/countries-50m.json"));

// Identical to build-map.js's NUM_TO_A3 — do not diverge without updating both
// files and D17's rationale for why they stay in lockstep.
const NUM_TO_A3 = {
  "024":"AGO","204":"BEN","072":"BWA","854":"BFA","108":"BDI","120":"CMR","132":"CPV","140":"CAF","148":"TCD","174":"COM","178":"COG","180":"COD","384":"CIV","262":"DJI","818":"EGY","226":"GNQ","232":"ERI","748":"SWZ","231":"ETH","266":"GAB","270":"GMB","288":"GHA","324":"GIN","624":"GNB","404":"KEN","426":"LSO","430":"LBR","434":"LBY","450":"MDG","454":"MWI","466":"MLI","478":"MRT","480":"MUS","504":"MAR","508":"MOZ","516":"NAM","562":"NER","566":"NGA","646":"RWA","678":"STP","686":"SEN","690":"SYC","694":"SLE","706":"SOM","710":"ZAF","728":"SSD","729":"SDN","834":"TZA","768":"TGO","788":"TUN","800":"UGA","894":"ZMB","716":"ZWE",
  "004":"AFG","050":"BGD","064":"BTN","104":"MMR","116":"KHM","144":"LKA","156":"CHN","356":"IND","360":"IDN","364":"IRN","368":"IRQ","408":"PRK","410":"KOR","418":"LAO","458":"MYS","524":"NPL","586":"PAK","598":"PNG","608":"PHL","626":"TLS","702":"SGP","704":"VNM","760":"SYR","764":"THA","887":"YEM","682":"SAU","512":"OMN",
  "068":"BOL","076":"BRA","170":"COL","188":"CRI","192":"CUB","214":"DOM","218":"ECU","222":"SLV","254":"GUF","320":"GTM","328":"GUY","332":"HTI","340":"HND","484":"MEX","558":"NIC","591":"PAN","600":"PRY","604":"PER","740":"SUR","862":"VEN","032":"ARG"
};

// Coordinate precision: round to 3 decimal places (~110m at the equator, well
// under a single screen pixel at any zoom this map reaches) to keep file size
// down without visibly changing the geometry MapLibre renders.
function roundCoords(node) {
  if (typeof node[0] === "number") {
    node[0] = Math.round(node[0] * 1000) / 1000;
    node[1] = Math.round(node[1] * 1000) / 1000;
    return node;
  }
  for (const child of node) roundCoords(child);
  return node;
}

const feats = topojson.feature(world, world.objects.countries).features;
const out = [];
for (const f of feats) {
  const a3 = NUM_TO_A3[String(f.id).padStart(3, "0")];
  if (!a3) continue;
  out.push({
    type: "Feature",
    properties: { iso3: a3, name: f.properties.name },
    geometry: { type: f.geometry.type, coordinates: roundCoords(f.geometry.coordinates) },
  });
}

const geo = { type: "FeatureCollection", features: out };
const file =
  "// GENERATED by scripts/build-map-geo.js from world-atlas (Natural Earth 50m, public domain).\n" +
  "// Do not edit by hand; rerun the generator instead.\n" +
  "window.LAUNCH_MAP_GEO = " +
  JSON.stringify(geo) + ";\n";

fs.writeFileSync(path.join(__dirname, "..", "data", "world-map-geo.js"), file);
console.log("Wrote data/world-map-geo.js — " + out.length + " countries, " + Math.round(file.length / 1024) + " KB");
